"""Add file type support

Revision ID: 31e110e9f88e
Revises: c4e4d22e47d5
Create Date: 2025-04-25 17:22:31.740507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31e110e9f88e'
down_revision: Union[str, None] = 'c4e4d22e47d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_sessions', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('analysis_sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('analysis_sessions', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('analysis_sessions', sa.Column('results', sa.JSON(), nullable=True))
    op.drop_column('analysis_sessions', 'session_name')
    op.add_column('uploaded_files', sa.Column('filepath', sa.String(length=512), nullable=False))
    op.add_column('uploaded_files', sa.Column('filesize', sa.Integer(), nullable=False))
    op.add_column('uploaded_files', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_column('uploaded_files', 'original_filename')
    op.drop_column('uploaded_files', 'file_size')
    op.drop_column('uploaded_files', 'upload_date')
    op.add_column('variable_definitions', sa.Column('file_id', sa.Integer(), nullable=True))
    op.add_column('variable_definitions', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('variable_definitions', sa.Column('label', sa.String(length=512), nullable=True))
    op.add_column('variable_definitions', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('variable_definitions', sa.Column('values', sa.JSON(), nullable=True))
    op.add_column('variable_definitions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('variable_definitions_session_id_fkey', 'variable_definitions', type_='foreignkey')
    op.create_foreign_key(None, 'variable_definitions', 'uploaded_files', ['file_id'], ['id'])
    op.drop_column('variable_definitions', 'variable_label')
    op.drop_column('variable_definitions', 'session_id')
    op.drop_column('variable_definitions', 'value_labels')
    op.drop_column('variable_definitions', 'variable_type')
    op.drop_column('variable_definitions', 'variable_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable_definitions', sa.Column('variable_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('variable_definitions', sa.Column('variable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('variable_definitions', sa.Column('value_labels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variable_definitions', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('variable_definitions', sa.Column('variable_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'variable_definitions', type_='foreignkey')
    op.create_foreign_key('variable_definitions_session_id_fkey', 'variable_definitions', 'analysis_sessions', ['session_id'], ['id'])
    op.drop_column('variable_definitions', 'created_at')
    op.drop_column('variable_definitions', 'values')
    op.drop_column('variable_definitions', 'type')
    op.drop_column('variable_definitions', 'label')
    op.drop_column('variable_definitions', 'name')
    op.drop_column('variable_definitions', 'file_id')
    op.add_column('uploaded_files', sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('uploaded_files', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('uploaded_files', sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('uploaded_files', 'uploaded_at')
    op.drop_column('uploaded_files', 'filesize')
    op.drop_column('uploaded_files', 'filepath')
    op.add_column('analysis_sessions', sa.Column('session_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('analysis_sessions', 'results')
    op.drop_column('analysis_sessions', 'settings')
    op.drop_column('analysis_sessions', 'description')
    op.drop_column('analysis_sessions', 'name')
    # ### end Alembic commands ###
