"""add indexed_path column to uploaded_files

Revision ID: ad46e332a4df
Revises: 51d7df124ad1
Create Date: 2025-04-27 16:52:31.462599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad46e332a4df'
down_revision: Union[str, None] = '51d7df124ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('indexed_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'indexed_path')
    # ### end Alembic commands ###
